---
node_exporter_version: 1.7.0
node_exporter_binary_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz

node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_web_telemetry_path: /metrics

node_exporter_enabled_collectors:
  - systemd
#  - filesystem:
#      ignored-mount-points: "^/(sys|proc|dev)($|/)"
#      ignored-fs-types: "^(sys|proc|auto)fs$"

node_exporter_disabled_collectors: []
node_exporter_binary_install_dir: /usr/local/bin
node_exporter_system_group: node-exp
node_exporter_system_user: "{{ node_exporter_system_group }}"
