---
grafana_gpg_key_url: https://apt.grafana.com/gpg.key

grafana_dashboards_dir: dashboards

grafana_instance: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

grafana_logs_dir: /var/log/grafana
grafana_data_dir: /var/lib/grafana

grafana_address: "0.0.0.0"
grafana_port: 3000

# External Grafana address. Variable maps to "root_url" in grafana server section
grafana_url: http://{{ grafana_address }}:{{ grafana_port }}
grafana_api_url: "{{ grafana_url }}"
grafana_domain: "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}"

grafana_config_dir: /etc/grafana
grafana_provisioning_dir: "{{ grafana_config_dir }}/provisioning"

# Additional options for grafana "server" section
# This section WILL omit options for: http_addr, http_port, domain, and root_url, as those settings are set by variables listed before
grafana_server:
  protocol: http
  enforce_domain: false
  socket: ""
  cert_key: ""
  cert_file: ""
  enable_gzip: false
  static_root_path: public
  router_logging: false
  serve_from_sub_path: false

grafana_datasources: []
