---
global:
  scrape_interval: 30s
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets: [localhost:9093]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/rules/*.yml

scrape_config_files:
  - /etc/prometheus/scrape_configs/*.yml

scrape_configs:
  - job_name: prometheus

    scrape_interval: 30s
    scrape_timeout: 10s

    static_configs:
      - targets:
          - localhost:9090
        labels:
          name: prometheus
          group: prometheus

  - job_name: prometheus-node-exporter

    scrape_interval: 30s
    scrape_timeout: 10s

    static_configs:
      - targets:
          - localhost:9100
        labels:
          name: prometheus
          group: prometheus
