---
- name: Install required packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - wget
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add Grafana GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: "{{ grafana_gpg_key_url }}"
    state: present

- name: Add Grafana Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present

- name: Install grafana
  become: true
  ansible.builtin.apt:
    pkg:
      - grafana
    state: present
  notify: restart grafana

- name: Configure Grafana
  ansible.builtin.include_tasks: configure.yml
