---
- name: Ensure data directory exists
  become: true
  ansible.builtin.file:
    path: "{{ docker_registry_data_dir }}"
    state: directory
    mode: "0755"

- name: Ensure docker daemon is running
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ensure docker registry network is available
  become: true
  community.docker.docker_network:
    name: "{{ docker_registry_network_name }}"

- name: Ensure docker registry is running
  become: true
  community.docker.docker_container:
    name: docker-registry-cache
    image: registry:2.8
    state: started
    network_mode: "{{ docker_registry_network_name }}"
    volumes:
      - /mnt/registry:/var/lib/registry
    env:
      REGISTRY_PROXY_REMOTEURL: "{{ docker_registry_proxy_remoteurl }}"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['*']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      Access-Control-Expose-Headers: "['Docker-Content-Digest']"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_DEBUG_ADDR: ":{{ docker_registry_metrics_port }}"
      REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: "true"
    restart_policy: always
    ports:
      - "{{ docker_registry_port }}:{{ docker_registry_port }}"
      - "{{ docker_registry_metrics_port }}:{{ docker_registry_metrics_port }}"

- name: Ensure docker registry ui is running
  become: true
  community.docker.docker_container:
    name: docker-registry-ui
    image: joxit/docker-registry-ui:main
    state: started
    network_mode: "{{ docker_registry_network_name }}"
    env:
      REGISTRY_TITLE: "{{ docker_registry_ui_title }}"
      THEME: light
      SINGLE_REGISTRY: "true"
      DELETE_IMAGES: "true"
      REGISTRY_URL: http://{{ ansible_default_ipv4.address }}:{{ docker_registry_port }}
      NGINX_PROXY_PASS_URL: http://{{ ansible_default_ipv4.address }}:{{ docker_registry_port }}
    restart_policy: always
    ports:
      - 80:80
  when: docker_registry_enable_ui
