---
- name: Create alertmanager system group
  become: true
  ansible.builtin.group:
    name: alertmanager
    system: true
    state: present

- name: Create alertmanager system user
  become: true
  ansible.builtin.user:
    name: alertmanager
    group: alertmanager
    system: true
    state: present
    shell: /usr/sbin/nologin
    create_home: false

- name: Create alertmanager directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: "0755"
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"

- name: Get binary
  block:
    - name: Download alertmanager binary to local folder
      ansible.builtin.get_url:
        url: "{{ alertmanager_binary_url }}"
        dest: /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
        mode: "0644"
      register: _download_binary

    - name: Unpack alertmanager binary
      ansible.builtin.unarchive:
        src: /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
        dest: /tmp
        creates: /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager
        remote_src: true

    - name: Install alertmanager executables
      become: true
      ansible.builtin.copy:
        src: /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}
        dest: /usr/local/bin
        mode: "0755"
        owner: root
        group: root
        remote_src: true
      with_items:
        - alertmanager
        - amtool
      notify: restart alertmanager

- name: Add alertmanager config
  become: true
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/alertmanager.yml"
    owner: alertmanager
    group: alertmanager
    mode: "0644"
  notify: restart alertmanager

- name: Create systemd service unit
  become: true
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - enable alertmanager
    - restart alertmanager

- name: Copy alertmanager template files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ alertmanager_config_dir }}/templates/"
    force: true
    owner: alertmanager
    group: alertmanager
    mode: "0644"
  with_fileglob: "{{ alertmanager_template_files }}"
  notify: restart alertmanager
