---
- name: Ensure gitlab-runner user exists on Ubuntu
  when: ansible_facts.distribution == 'Ubuntu'
  block:
    # On Ubuntu we create the gitlab-runner user as a system user
    - name: Make sure gitlab-runner group exists
      become: true
      ansible.builtin.group:
        name: "{{ gitlab_runner_user_group }}"
        system: true
        state: present

    - name: Make sure gitlab-runner user exists
      become: true
      ansible.builtin.user:
        name: "{{ gitlab_runner_user }}"
        group: "{{ gitlab_runner_user_group }}"
        system: true
        state: present
        shell: /usr/sbin/nologin
        create_home: false

- name: Ensure gitlab-runner user exists on MacOS
  when: ansible_facts.distribution == 'MacOSX'
  block:
    # On MacOS the runner should be a normal user
    # so we just make sure it exists
    - name: Make sure gitlab-runner group exists
      ansible.builtin.group:
        name: "{{ gitlab_runner_user_group }}"
        state: present

    - name: Make sure gitlab-runner user exists
      ansible.builtin.user:
        name: "{{ gitlab_runner_user }}"
        group: "{{ gitlab_runner_user_group }}"
        state: present

- name: Ensure gitlab-runner user exists on Windows
  when: ansible_facts.os_family == 'Windows'
  block:
    # On Windows, Gitlab-Runner user needs to be an administrator
    - name: Make sure gitlab-runner user exists
      ansible.windows.win_user:
        name: "{{ gitlab_runner_user }}"
        password: "{{ gitlab_runner_user_password }}"
        state: present
        groups:
          - Administrators

- name: Ensure gitlab-runner user is added to any extra groups
  when: ansible_facts.os_family != 'Windows'
  become: true
  ansible.builtin.user:
    name: gitlab-runner
    groups: "{{ gitlab_runner_user_extra_groups }}"
    append: true
