---
- name: Create Gitlab-Runner Dest File
  ansible.windows.win_file:
    path: "{{ gitlab_runner_binary_install_dir }}"
    state: directory

- name: Download Latest Gitlab-Runner binary
  ansible.windows.win_get_url:
    url: "{{ gitlab_runner_windows_exe_url }}"
    dest: "{{ gitlab_runner_binary_install_dir }}\\gitlab-runner.exe"

- name: Get info for gitlab-runner service
  ansible.windows.win_service_info:
    name: gitlab-runner
  register: __gitlab_runner_service_info

- name: Install gitlab-runner service if it's not already present
  ansible.windows.win_shell: .\gitlab-runner.exe install
  args:
    chdir: "{{ gitlab_runner_binary_install_dir }}"
  when:
    not __gitlab_runner_service_info.exists

- name: Get info for gitlab-runner service again
  ansible.windows.win_service_info:
    name: gitlab-runner
  register: __gitlab_runner_service_info

- name: Start Gitlab-Runner Service if it's not started
  ansible.windows.win_shell: .\gitlab-runner.exe start
  args:
    chdir: "{{ gitlab_runner_binary_install_dir }}"
  when:
    __gitlab_runner_service_info.services[0].state != "started"
