---
- name: Setup docker on {{ ansible_facts['distribution'] }}.
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] | lower }}.yml"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Setup docker on {{ ansible_facts['distribution'] }}.
  ansible.builtin.include_tasks: windows.yml
  when: ansible_facts['distribution'] == 'Microsoft Windows Server 2022 Standard'
