---
- name: Enable Vmware Exporter
  become: true
  ansible.builtin.systemd:
    name: vmware_exporter
    enabled: true
  listen: enable vmware exporter

- name: Restart Vmware Exporter
  become: true
  ansible.builtin.systemd:
    name: vmware_exporter
    state: restarted
    daemon_reload: true
  listen: restart vmware exporter
