---
- name: Cleanup gitlab runner build directories on Windows every Saturday
  when: ansible_facts.os_family == 'Windows'
  community.windows.win_scheduled_task:
    name: Clear out gitlab runner build directories
    actions:
      - path: powershell
        arguments: "rm -r {{cleanup_windows_gitlab_build_dir}}\\*"
    triggers:
      - type: weekly
        days_of_week: sunday
        start_boundary: "2017-10-09T09:00:00"
    username: SYSTEM
    run_level: highest
    state: present
    enabled: true
